{{- if .Values.certManager.clusterIssuer.enabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.certManager.clusterIssuer.name }}
spec:
  acme:
    email: {{ .Values.certManager.clusterIssuer.email }}
    server: {{ .Values.certManager.clusterIssuer.server }}
    privateKeySecretRef:
      name: {{ .Values.certManager.clusterIssuer.name }}-account-key
    solvers:
      - http01:
          ingress:
            class: {{ .Values.certManager.clusterIssuer.ingressClass }}
{{- end }}
