{{- if and .Values.keycloak.enabled .Values.keycloak.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: keycloak-postgres
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
    - name: postgres
      port: {{ .Values.keycloak.postgres.servicePort }}
      targetPort: {{ .Values.keycloak.postgres.servicePort }}
  selector:
    app: keycloak-postgres
{{- end }}
