{{- if and .Values.keycloak.enabled .Values.keycloak.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-keycloak
  namespace: {{ .Values.namespace }}
  annotations:
    {{- with .Values.keycloak.ingress.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.keycloak.ingress.className }}
  {{- with .Values.keycloak.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    - host: {{ .Values.keycloak.hostname | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: keycloak
                port:
                  number: {{ .Values.keycloak.service.port }}
{{- end }}
