{{- if .Values.keycloak.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  KEYCLOAK_ADMIN: {{ .Values.keycloak.adminUser }}
  KEYCLOAK_ADMIN_PASSWORD: {{ .Values.keycloak.adminPassword }}
  KC_DB_USERNAME: {{ .Values.keycloak.postgres.username }}
  KC_DB_PASSWORD: {{ .Values.keycloak.postgres.password }}
{{- end }}
